backend:
  name: github
  repo: pjoseph91/almaart-website
  branch: main
  base_url: https://almaart-website.pjoseph9191.workers.dev

media_folder: public/images
public_folder: /images

collections:
  - name: pages
    label: 페이지
    folder: src/pages
    extension: astro
    format: frontmatter
    create: false
    files:
      - name: index
        label: 홈페이지
        file: src/pages/index.astro
        fields:
          - label: 페이지 정보
            name: page_info
            widget: object
            fields:
              - { label: "제목", name: "title", widget: "string" }

      - name: about
        label: 소개 페이지
        file: src/pages/about.astro
        fields:
          - label: 페이지 정보
            name: page_info
            widget: object
            fields:
              - { label: "제목", name: "title", widget: "string" }

      - name: spaces
        label: 공간 페이지
        file: src/pages/spaces.astro
        fields:
          - label: 페이지 정보
            name: page_info
            widget: object
            fields:
              - { label: "제목", name: "title", widget: "string" }

      - name: programs
        label: 프로그램 페이지
        file: src/pages/programs.astro
        fields:
          - label: 페이지 정보
            name: page_info
            widget: object
            fields:
              - { label: "제목", name: "title", widget: "string" }

      - name: contact
        label: 오시는 길 페이지
        file: src/pages/contact.astro
        fields:
          - label: 페이지 정보
            name: page_info
            widget: object
            fields:
              - { label: "제목", name: "title", widget: "string" }

      - name: reservations
        label: 예약·신청 페이지
        file: src/pages/reservations.astro
        fields:
          - label: 페이지 정보
            name: page_info
            widget: object
            fields:
              - { label: "제목", name: "title", widget: "string" }

      - name: support
        label: 후원 페이지
        file: src/pages/support.astro
        fields:
          - label: 페이지 정보
            name: page_info
            widget: object
            fields:
              - { label: "제목", name: "title", widget: "string" }
